### ISSUE TITLE
'..pasta edit' broken

### ISSUE THREAD

**Issue by ThomasTherkelsen** [skuldbot/Skuld#63]
`..pasta edit` unable to edit a pasta, generating an error `Error changing content of [pasta]`
![image](https://user-images.githubusercontent.com/37107686/74681045-ac090900-51c2-11ea-80f2-305e27a81e5e.png)

**Comment by exsersewo** [comment]
Fixed with e295ad2012dfbaf19442cd96e13dd46646ac75d4
