### ISSUE TITLE
Ping users who ran a command

### ISSUE THREAD

**Issue by KatalystPrime** [skuldbot/Skuld#91]
It's quite hard to tell sometimes which message is for whom when there are multiple people running the same command (such as mia). It does state who executed any command, but regardless, it should make it clearer to differentiate them.

**Comment by exsersewo** [comment]
Are you saying ping users for **ALL** commands used or for specific module(s)? In your example ping users who use a command in the Gambling module?

**Comment by KatalystPrime** [comment]
I'd say for specific modules, like the gambling one, but that creates a consistency issue.

**Comment by exsersewo** [comment]
Consistency is not a problem within regards to removing ambiguity.

**Comment by KatalystPrime** [comment]
It could be an option users can change based on preference.
