### ISSUE TITLE
Recurring Reminders

### ISSUE THREAD

**Issue by KatalystPrime** [skuldbot/Skuld#95]
Ability to create reminders that well, recur.
Either as a new command or as an extension of the current command.
something like "Remind me at 12:00 every day" or "remind me at 12:00 every 2 days".

**Comment by exsersewo** [comment]
This already exists you use the —repeat argument
![C0FBF97C-CFC6-4412-B43F-75FA64920D66](https://user-images.githubusercontent.com/25526843/83967361-852d2a80-a8b8-11ea-8cf1-09370cfdd592.jpeg)
